[package]
name = "vpga-graph"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
queues = "1.1.0"
rand = "0.8.5"
uuid = { version = "1.4.1", features = ["serde", "v4", "fast-rng"] }
